Algoritmo "exercícioa"
//
//
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição :
// Autor(a) : Beatriz Francelino Borges Carneiro
// Data atual :0/09/2021
Var
// Seção de Declarações das variáveis
num, i: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval ("Escolha um número: ")
 Leia (num)
 Enquanto i <= 10 faca
 Escreval ( i , " *", num, " =", i*num)
 i<-i+1
 FimEnquanto

Fimalgoritmo