Algoritmo "exemplo2"
//
//
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição :  Introdução a estrutura de repetição PARA
//
//
//
//
// Autor(a) : Beatriz Francelino Borges Carneiro
// Data atual :0/09/2021
Var
// Seção de Declarações das variáveis
  cont : Inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
  Para cont de 1 ate 10 passo 1 faca
      Escreval (cont)
   FimPara

Fimalgoritmo